site_name: Learn Valkey
site_url: https://www.patashale.in/learn-valkey/
site_author: Patashale™
site_description: Learn everything about Valkey here at Patashale™.
repo_url: https://github.com/patashale/learn-valkey
repo_name: patashale/learn-valkey
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: "#123678"

nav:
  - Home: index.md
  - Data Types:
    - Overview: en/data-types/overview.md
    - String: 
      - Overview: en/data-types/string.md
    - List: 
      - Overview: en/data-types/list.md
    - Set: 
      - Overview: en/data-types/set.md
    - Sorted Set: 
      - Overview: en/data-types/sorted-set.md
    - Hash: 
      - Overview: en/data-types/hash.md
    - HyperLogLog: 
      - Overview: en/data-types/hyperloglog.md
    - Bitmap: 
      - Overview: en/data-types/bitmap.md
    - Bitfield: 
      - Overview: en/data-types/bitfield.md
    - Geospatial: 
      - Overview: en/data-types/geospatial.md
    - Stream: 
      - Overview: en/data-types/stream.md
    - Pub/Sub: 
      - Overview: en/data-types/pub-sub.md
    - JSON: 
      - Overview:  en/data-types/json.md
    - Time Series: 
      - Overview: en/data-types/time-series.md
    - Bloom Filter: 
      - Overview: en/data-types/bloom-filter.md
    - Cuckoo Filter: 
      - Overview:  en/data-types/cuckoo-filter.md
    - Count-min Sketch: 
      - Overview: en/data-types/count-min-sketch.md
    - Top-K: 
      - Overview: en/data-types/top-k.md
    - T-Digest: 
      - Overview: en/data-types/t-digest.md
  - Commands:
    - Overview: en/commands/overview.md
    - Generic:
      - Overview: en/commands/generic.md
    - Cluster Management:
      - Overview: en/commands/cluster-management.md
    - Server Management:
      - Overview: en/commands/server-management.md
    - Connection Management:
      - Overview: en/commands/connection-management.md
    - Transactions:
      - Overview: en/commands/transactions.md
    - Lua Scripting:
      - Overview: en/commands/scripting-and-functions.md
    - Triggers & Functions:
      - Overview: en/commands/triggers-and-functions.md
    - Search & Query:
      - Overview: en/commands/search-and-query.md
  - Orchestration:
    - Overview: en/orchestration/overview.md
    - Security:
      - Overview: en/orchestration/security.md
    - Scaling:
      - Overview: en/orchestration/scaling.md
    - Replication:
      - Overview: en/orchestration/replication.md
    - Persistence:
      - Overview: en/orchestration/persistence.md
    - Performance:
      - Overview: en/orchestration/performance.md
    - Debugging:
      - Overview: en/orchestration/debugging.md
  - Patterns:
    - Overview: en/patterns/overview.md

copyright: Copyright &copy; 2023 Patashale™
